//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ModelViewer.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MVTYPE                      129
#define IDD_GRID                        132
#define IDD_BOUNDING_BOX                133
#define IDD_SCALAR_DATA                 135
#define IDD_VECTOR_DATA                 136
#define IDD_VECTOR_OPTIONS              137
#define IDD_DATA_SELECTION              138
#define IDD_EXPORT_ANIMATION            139
#define IDD_ANIMATION                   140
#define IDD_CROP_CONTROLS               144
#define IDD_CROP_OPTIONS                145
#define IDD_DISPLAY_SIZE                146
#define IDD_COLOR_BAR_LIMITS            147
#define IDD_COLOR_BAR_TEXT              148
#define IDD_ANIMATION_CONTROLS          149
#define IDD_ANIMATION_OPTIONS           150
#define IDD_PREFERENCES                 151
#define IDD_IMAGE_GENERATION            152
#define IDD_BITMAP_RESOLUTION           153
#define IDD_COLOR_BAR_SIZE              154
#define IDR_NOT_USED                    156
#define IDD_DIALOG1                     157
#define IDD_OVERLAY                     159
#define IDD_OVERLAY_CONTROLS            160
#define IDD_OVERLAY_FILE                161
#define IDD_OVERLAY_BOUNDS              162
#define IDD_MODFLOW6_DATA_FILES         177
#define IDD_PREVIEW_TOOLBAR             201
#define IDD_DATA                        202
#define IDD_LIGHTING                    204
#define IDD_CROP                        208
#define IDD_REGULAR_ISOSURFACE          209
#define IDD_CUSTOM_ISOSURFACE           210
#define IDD_GRID_LINES                  212
#define IDD_GRID_SHELL                  213
#define IDD_AXES                        214
#define IDD_ISOSURFACE                  216
#define IDD_LIGHTS                      217
#define IDD_SURFACE                     218
#define IDD_GEOMETRY                    219
#define IDD_BACKGROUND                  220
#define IDD_SCALE                       222
#define IDD_SOLID                       223
#define IDD_COLOR_BAR                   224
#define IDD_VECTOR_CONTROLS             226
#define IDD_VECTOR                      227
#define IDD_PATHLINES                   228
#define IDD_SUBGRID                     229
#define IDD_VECTOR_THRESHOLD            230
#define IDD_PATHLINES_DISPLAY           231
#define IDD_MODEL_FEATURES              233
#define IDD_PATHLINES_COLOR             234
#define IDD_PATHLINES_CLIPPING          235
#define IDD_PATHLINE_DATA               236
#define IDD_COLOR_BAR_COLORS            242
#define IDD_CROP_VECTORS                243
#define IDD_COLOR_BAR_SOURCE            244
#define IDD_GRID_DISPLAY                245
#define IDC_SOLID_DISPLAY_BLOCKY        1000
#define IDC_ISOSURFACE_MAX              1000
#define IDC_X_SLIDER                    1000
#define IDC_SOLID_DISPLAY_SMOOTH        1001
#define IDC_ISOSURFACE_MIN              1001
#define IDC_Y_SLIDER                    1001
#define IDC_NUMBER_OF_ISOSURFACES       1002
#define IDC_Z_SLIDER                    1002
#define IDC_SHOW_GLYPH                  1002
#define IDC_AUXILIARY_LIGHT_POSITION    1003
#define IDC_MIN                         1003
#define IDC_LINE                        1004
#define IDC_MAX                         1004
#define IDC_GLYPH_SPIN                  1004
#define IDC_BROWSE                      1005
#define IDC_VALUE_RED                   1005
#define IDC_TUBE                        1005
#define IDC_SCALE_FACTOR                1005
#define IDC_VALUE_BLUE                  1006
#define IDC_AXES_SIZE                   1006
#define IDC_IMIN                        1006
#define IDC_Z_ORIGIN                    1007
#define IDC_IMAX                        1007
#define IDC_AXES_TUBE_DIAMETER          1008
#define IDC_JMIN                        1008
#define IDC_TIME_POINT_LABELS           1009
#define IDC_Y_ORIGIN                    1009
#define IDC_JMAX                        1009
#define IDC_ACTIVATE_X                  1010
#define IDC_X_ORIGIN                    1010
#define IDC_KMIN                        1010
#define IDC_OPACITY                     1011
#define IDC_DATA_TYPE_CHOOSER           1011
#define IDC_DONE                        1011
#define IDC_KMAX                        1011
#define IDC_ACTIVATE_Y                  1012
#define IDC_APPLY                       1012
#define IDC_IRATE                       1012
#define IDC_JRATE                       1013
#define IDC_REMOVE                      1013
#define IDC_ACTIVATE_Z                  1014
#define IDC_KRATE                       1014
#define IDC_SOLID_THRESHOLD_MAX         1015
#define IDC_GRAY                        1015
#define IDC_SOLID_THRESHOLD_MIN         1016
#define IDC_AMBIENT_SLIDER              1016
#define IDC_DELAY                       1016
#define IDC_BLACK                       1016
#define IDC_APPLY_THRESHOLD             1017
#define IDC_DIFFUSE_SLIDER              1017
#define IDC_PROP_SHEET                  1017
#define IDC_WHITE                       1017
#define IDC_FULL_SOLID                  1018
#define IDC_SPECULAR_SLIDER             1018
#define IDC_AUXILIARY_LIGHT_INTENSITY_SLIDER 1018
#define IDC_XMIN                        1018
#define IDC_SPECULAR_POWER_SLIDER       1019
#define IDC_HEADLIGHT                   1019
#define IDC_IMIN_SPIN                   1019
#define IDC_AMBIENT                     1020
#define IDC_AUXILIARY_LIGHT             1020
#define IDC_JMIN_SPIN                   1020
#define IDC_DIFFUSE                     1021
#define IDC_HEADLIGHT_INTENSITY_SLIDER  1021
#define IDC_XMAX                        1021
#define IDC_KMIN_SPIN                   1021
#define IDC_SPECULAR                    1022
#define IDC_AUXILIARY_LIGHT_INTENSITY   1022
#define IDC_DEFAULT                     1022
#define IDC_YMIN                        1022
#define IDC_SPECULAR_POWER              1023
#define IDC_HEADLIGHT_INTENSITY         1023
#define IDC_RED                         1023
#define IDC_YMAX                        1023
#define IDC_FULL_RANGE                  1024
#define IDC_GREEN                       1024
#define IDC_ZMIN                        1024
#define IDC_BLUE                        1025
#define IDC_ZMAX                        1025
#define IDC_REVERSE                     1025
#define IDC_XSCALE                      1026
#define IDC_TRACKBALL_MODE              1026
#define IDC_BLUE_SLIDER                 1026
#define IDC_XMAX_SPIN                   1026
#define IDC_YSCALE                      1027
#define IDC_JOYSTICK_MODE               1027
#define IDC_GREEN_SLIDER                1027
#define IDC_ISOSURFACE_LIST             1027
#define IDC_XMIN_SPIN                   1027
#define IDC_ZSCALE                      1028
#define IDC_IMAGE_COARSE                1028
#define IDC_RED_SLIDER                  1028
#define IDC_DELETE                      1028
#define IDC_XDELTA                      1028
#define IDC_IMAGE_FINE                  1029
#define IDC_ADD                         1029
#define IDC_YDELTA                      1029
#define IDC_WHITE_BACKGROUND            1029
#define IDC_VALUE                       1030
#define IDC_ZDELTA                      1030
#define IDC_YMIN_SPIN                   1031
#define IDC_RESOLUTION_SCREEN           1031
#define IDC_CUSTOM_BACKGROUND           1031
#define IDC_YMAX_SPIN                   1032
#define IDC_RESOLUTION_150              1032
#define IDC_TIME_CHOOSER                1033
#define IDC_ZMIN_SPIN                   1033
#define IDC_RESOLUTION_300              1033
#define IDC_ZMAX_SPIN                   1034
#define IDC_BMP_WIDTH_OPTION            1034
#define IDC_RUN_ANIMATION               1034
#define IDC_BMP_HEIGHT_OPTION           1035
#define IDC_STOP_ANIMATION              1035
#define IDC_CROP_ANGLE                  1035
#define IDC_IMAX_SPIN                   1035
#define IDC_BMP_WIDTH                   1036
#define IDC_SET_TO_TIME_POINT           1036
#define IDC_CROP_ANGLE_SPIN             1036
#define IDC_JMAX_SPIN                   1036
#define IDC_BMP_HEIGHT                  1037
#define IDC_KMAX_SPIN                   1037
#define IDC_NAME_FILE                   1038
#define IDC_CURRENT_TIME                1038
#define IDC_GWF_MODEL_NAME_FILE         1038
#define IDC_ADVANCE_ANIMATION           1039
#define IDC_BROWSE_NAME                 1041
#define IDC_OPACITY_SLIDER              1041
#define IDC_BROWSE_GWF_MODEL_NAME_FILE  1041
#define IDC_XSYNC                       1042
#define IDC_SHOW_CROPPED_AWAY           1042
#define IDC_YSYNC                       1043
#define IDC_COLOR_BANDS                 1043
#define IDC_POSITION_Y                  1044
#define IDC_ZSYNC                       1044
#define IDC_ACTIVATE_SUBGRID            1044
#define IDC_POSITION_Z                  1045
#define IDC_LOG_SCALE                   1045
#define IDC_APPLY_VECTOR_THRESHOLD      1046
#define IDC_POSITION_X                  1047
#define IDC_FILE_PREFIX                 1047
#define IDC_VECTOR_MIN                  1047
#define IDC_POSITION_X_SPIN             1048
#define IDC_START_INDEX                 1048
#define IDC_VECTOR_MAX                  1048
#define IDC_POSITION_Y_SPIN             1049
#define IDC_END_INDEX                   1049
#define IDC_POSITION_Z_SPIN             1050
#define IDC_OUTPUT_FOLDER               1050
#define IDC_VECTOR_RANGE_LABEL          1050
#define IDC_TUBE_DIAMETER               1051
#define IDC_DATA_TYPE_COMBO             1052
#define IDC_DISPLAY_WIDTH               1053
#define IDC_FILE_START_NUMBER           1054
#define IDC_DISPLAY_HEIGHT              1054
#define IDC_NUMBER_OF_FILES             1055
#define IDC_ILOW                        1055
#define IDC_DISK_SPACE_REQUIRED         1056
#define IDC_IHIGH                       1056
#define IDC_ROTATE                      1057
#define IDC_JLOW                        1057
#define IDC_ELEVATE                     1058
#define IDC_JHIGH                       1058
#define IDC_PREVIEW                     1059
#define IDC_KLOW                        1059
#define IDC_ROTATE_VIEWPOINT            1060
#define IDC_KHIGH                       1060
#define IDC_ELEVATE_VIEWPOINT           1061
#define IDC_ILOW_SPIN                   1061
#define IDC_IHIGH_SPIN                  1062
#define IDC_JLOW_SPIN                   1063
#define IDC_JHIGH_SPIN                  1064
#define IDC_KLOW_SPIN                   1065
#define IDC_KHIGH_SPIN                  1066
#define IDC_NO_PATHLINE_CLIPPING        1078
#define IDC_CLIP_BY_SIMTIME             1079
#define IDC_CLIP_BY_TIME_RANGE          1080
#define IDC_MINIMUM_TIME                1081
#define IDC_MAXIMUM_TIME                1082
#define IDC_ACTIVATE_OUTLINE            1083
#define IDC_SET_TO                      1084
#define IDC_CURRENT                     1085
#define IDC_TO_VISUALIZE                1086
#define IDC_FONT_SIZE                   1090
#define IDC_WIDTH                       1091
#define IDC_HEIGHT                      1092
#define IDC_OFFSET                      1093
#define IDC_NUM_LABELS                  1094
#define IDC_PRECISION                   1095
#define IDC_SHOW_LIST                   1096
#define IDC_HIDE_LIST                   1097
#define IDC_SHOW_FEATURE                1098
#define IDC_HIDE_FEATURE                1099
#define IDC_MOVE_TO_TOP                 1100
#define IDC_MOVE_TO_BOT                 1101
#define IDC_MOVE_DOWN                   1102
#define IDC_MOVE_UP                     1103
#define IDC_MODEL_FEATURE_COLOR         1104
#define IDC_MODEL_FEATURE_SIZE          1105
#define IDC_MODEL_FEATURE_SIZE_TEXT     1106
#define IDC_SOLID_DISPLAY_BANDED        1106
#define IDC_XORIG                       1108
#define IDC_YORIG                       1109
#define IDC_ANGLE                       1112
#define IDC_OVERLAY_ELEV                1113
#define IDC_OVERLAY_TYPE                1114
#define IDC_BROWSE_OVERLAY              1115
#define IDC_OVERLAY_FILE                1116
#define IDC_OVERLAY_SCALE               1117
#define IDC_OVERLAY_TRIM                1118
#define IDC_DRAPE_GAP                   1119
#define IDC_OVERLAY_FLAT                1120
#define IDC_OVERLAY_DRAPE               1121
#define IDC_OVERLAY_XMIN                1122
#define IDC_OVERLAY_XMAX                1123
#define IDC_OVERLAY_YMIN                1124
#define IDC_OVERLAY_YMAX                1125
#define IDC_MV_VERSION                  1126
#define IDC_COMBO_COLOR_SCHEME          1144
#define IDC_LowerColorButton            1149
#define IDC_UpperColorButton            1150
#define IDC_FIRST_LIST                  1152
#define IDC_LAST_LIST                   1153
#define IDC_LogTransform                1156
#define IDC_OVERLAY_CROP                1159
#define IDC_COMBO_ANIMATION_TYPE        1161
#define IDC_ANIMATION_TYPE              1163
#define IDC_EDIT_NUMBER_OF_STEPS        1164
#define IDC_NUMBER_OF_STEPS             1165
#define IDC_COMBO_EXPORT_ANIMATION_TYPE 1167
#define IDC_EXPORT_NUMBER_OF_STEPS      1168
#define IDC_EDIT_EXPORT_NUMBER_OF_STEPS 1169
#define IDC_CLIP_BY_MAXIMUM_TIME        1171
#define IDC_CLIP_BY_MINIMUM_TIME        1172
#define IDC_CHECK_LOG_TRANSPORT         1172
#define IDC_LINE_WIDTH                  1173
#define IDC_COMBO_DATA_SOURCE           1174
#define IDC_SPECIFY_MODFLOW6_NAME_FILE  1178
#define IDC_SPECIFY_MODFLOW6_DATA_FILES 1179
#define IDC_GWF_MODEL_GRID_FILE         1180
#define IDC_GWF_MODEL_HEAD_FILE         1181
#define IDC_GWF_MODEL_BUDGET_FILE       1182
#define IDC_BROWSE_GWF_MODEL_GRID_FILE  1183
#define IDC_BROWSE_GWF_MODEL_HEAD_FILE  1184
#define IDC_BROWSE_GWf_MOLDE_BUDGET_FILE 1185
#define IDC_BROWSE_GWF_MODEL_BUDGET_FILE 1185
#define IDC_GRID_DISPLAY_INTERPOLATED   1186
#define IDC_RADIO2                      1187
#define IDC_GRID_DISPLAY_STAIRSTEPPED   1187
#define IDC_MV_RELEASE                  1188
#define ID_PREFERENCES                  32771
#define ID_SHOW_AXES                    32772
#define ID_COPY_DISPLAY_TO_CLIPBOARD    32774
#define ID_FIT_DISPLAY_IN_WINDOW        32775
#define ID_RECALL_VIEWPOINT             32776
#define ID_VIEW_FROM_NEXT_DIRECTION     32777
#define ID_VIEW_FROM_PX                 32778
#define ID_VIEW_FROM_NX                 32779
#define ID_EXPORT_AS_BMP                32780
#define ID_VIEW_FROM_NY                 32781
#define ID_VIEW_FROM_PZ                 32782
#define ID_VIEW_FROM_NZ                 32783
#define ID_EXPORT_ANIMATION             32784
#define ID_GRID_TOOL                    32787
#define ID_GEOMETRY_TOOL                32788
#define ID_VIEW_FROM_PY                 32789
#define ID_SHOW_NONE                    32790
#define ID_SHOW_SOLID                   32794
#define ID_EXPORT_AS_VRML               32795
#define ID_SHOW_ISOSURFACES             32796
#define ID_SAVE_VIEWPOINT               32797
#define ID_SHOW_GRID_SHELL              32798
#define ID_SHOW_BOUNDING_BOX            32799
#define ID_SHOW_GRID_LINES              32800
#define ID_SHOW_TITLE                   32801
#define ID_PERSPECTIVE_PROJECTION       32802
#define ID_PARALLEL_PROJECTION          32803
#define ID_COLOR_BAR_TOOL               32804
#define ID_LIGHTING_TOOL                32806
#define ID_SOLID_TOOL                   32808
#define ID_ISOSURFACE_TOOL              32809
#define ID_CROP_TOOL                    32810
#define ID_ANIMATION_TOOL               32811
#define ID_SHOW_COLOR_BAR               32812
#define ID_LOAD_DATA                    32813
#define ID_SHOW_VECTORS                 32814
#define ID_VECTOR_TOOL                  32815
#define ID_SHOW_PATHLINES               32817
#define ID_PATHLINES_TOOL               32818
#define ID_SHOW_TIME                    32819
#define ID_DATA_TOOL                    32820
#define ID_DISPLAY_SIZE                 32823
#define ID_SHOW_MODEL_FEATURES          32826
#define ID_MODEL_FEATURES_TOOL          32827
#define ID_CUSTOM_FILE_CLOSE            32829
#define ID_HELP_CONTENTS                32831
#define ID_SHOW_PARTICLES               32832
#define ID_PARTICLES_TOOL               32833
#define ID_SHOW_PARTICLE                32834
#define ID_SHOW_OVERLAY                 32835
#define ID_OVERLAY_TOOL                 32836
#define ID_AXES_TOOL                    32837
#define ID_ACTION_ADVANCED              32838
#define ID_INDICATOR_MODEL_NAME         59142
#define ID_INDICATOR_DATA_NAME          59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1189
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
