
#define MV_VERSION "MF6"

#define MV_SOLID_SMOOTH 0
#define MV_SOLID_BLOCKY 1
#define MV_SOLID_BANDED 2

#define MV_GRID_INTERPOLATED 0
#define MV_GRID_STAIRSTEPPED 1

#define MV_PATHLINE_TUBE 0
#define MV_PATHLINE_LINE 1

#define MV_CELL_SCALARS 0
#define MV_POINT_SCALARS 1

#define MV_GRID_NOT_DEFINED 0
#define MV_STRUCTURED_GRID 4
#define MV_LAYERED_GRID 5
#define MV_UNSTRUCTURED_GRID 6

#define MV_INITIAL_DISPLAY_BOUNDING_BOX 0
#define MV_INITIAL_DISPLAY_GRID_OUTLINE 1

#define MV_USE_CELL_DATA_FOR_RANGE 0
#define MV_USE_POINT_DATA_FOR_RANGE 1

#define MP_TRAVEL_TIME 0
#define MP_MIN_TRAVEL_TIME 1
#define MP_MAX_TRAVEL_TIME 2
